cros kernel

diff --git a/kernel/build b/kernel/build
--- a/kernel/build
+++ b/kernel/build
@@ -14,45 +14,61 @@ cd $CADMIUMROOT/tmp
 
 # check if kernel has been downloaded this week, if not download/update it
 if [ "$(date +'%V%y') $KERNEL" != "$(cat kern-dl-date-$BASEBOARD 2>/dev/null)" ]; then
-	echo "Downloading kernel for $BASEBOARD/$TARGET"
-	rm -rf linux-$BASEBOARD
+	case $KERNEL in
+		cros)
+			rm -rf linux-$BASEBOARD
+			mkdir -p linux-$BASEBOARD
+			cd linux-$BASEBOARD
+			git clone https://chromium.googlesource.com/chromiumos/third_party/kernel.git --single-branch --depth 1 -b $CROS_KERN_BRANCH ./
+			for x in $(echo chromeos/config/*.config chromeos/config/$ARCH/common.config chromeos/config/$ARCH/*mediatek.flavour.config); do
+				echo "Applying $x config"
+				cat $x | grep -v "CONFIG_SECURITY" | grep -v "CONFIG_DEBUG_INFO" | grep -v "CORESIGHT" >> .config
+			done
+			echo "KBUILD_CFLAGS += -Wno-error" >> Makefile
+			yes "" | make config # *shrugs*
+			;;
+		*)
+			echo "Downloading $KERNEL kernel for $BASEBOARD/$TARGET"
+			rm -rf linux-$BASEBOARD
+	
+			if [ "$BASEBOARD" = "kukui" ]; then #      -.-
+				if [ $KERNEL = libre ]; then
+					curl -L https://linux-libre.fsfla.org/pub/linux-libre/releases/5.10.25-gnu/linux-libre-5.10.25-gnu.tar.xz -o Linux-archive
+				else
+					curl -L https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.25.tar.xz -o Linux-archive
+				fi
+			else
+				if [ $KERNEL = libre ]; then
+					curl -L "https://linux-libre.fsfla.org/pub/linux-libre/releases/LATEST-5.N/$(curl https://linux-libre.fsfla.org/pub/linux-libre/releases/LATEST-5.N/ | egrep -o 'linux-libre-....-gnu.tar.xz' | head -n1)" -o Linux-archive
+				else
+					curl -L "$(curl -sL https://www.kernel.org/ | grep "Download complete tarball" | head -n1 | tr '"' ' ' | awk '{print $3}')" -o Linux-archive
+				fi
+			fi
+			mkdir linux-$BASEBOARD
+			bsdtar xf Linux-archive --strip-components=1 -C linux-$BASEBOARD
+			echo "$(date +'%V%y') $KERNEL" > kern-dl-date-$BASEBOARD
 
-	if [ "$BASEBOARD" = "kukui" ]; then #      -.-
-		if [ $KERNEL = libre ]; then
-			curl -L https://linux-libre.fsfla.org/pub/linux-libre/releases/5.10.25-gnu/linux-libre-5.10.25-gnu.tar.xz -o Linux-archive
-		else
-			curl -L https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.25.tar.xz -o Linux-archive
-		fi
-	else
-		if [ $KERNEL = libre ]; then
-			curl -L "https://linux-libre.fsfla.org/pub/linux-libre/releases/LATEST-5.N/$(curl https://linux-libre.fsfla.org/pub/linux-libre/releases/LATEST-5.N/ | egrep -o 'linux-libre-....-gnu.tar.xz' | head -n1)" -o Linux-archive
-		else
-			curl -L "$(curl -sL https://www.kernel.org/ | grep "Download complete tarball" | head -n1 | tr '"' ' ' | awk '{print $3}')" -o Linux-archive
-		fi
-	fi
-	mkdir linux-$BASEBOARD
-	bsdtar xf Linux-archive --strip-components=1 -C linux-$BASEBOARD
-	echo "$(date +'%V%y') $KERNEL" > kern-dl-date-$BASEBOARD
+			cd linux-$BASEBOARD
 
-	cd linux-$BASEBOARD
+			for x in $(ls $CADMIUMROOT/baseboard/$BASEBOARD/patches/*.patch); do
+				echo "Applying $x"
+				patch -p1 --forward < $x || true
+			done
+			for x in $(ls $CADMIUMROOT/board/$TARGET/patches/*.patch); do
+				echo "Applying $x"
+				patch -p1 --forward < $x || true
+			done
 
-	for x in $(ls $CADMIUMROOT/baseboard/$BASEBOARD/patches/*.patch); do
-		echo "Applying $x"
-		patch -p1 --forward < $x || true
-	done
-	for x in $(ls $CADMIUMROOT/board/$TARGET/patches/*.patch); do
-		echo "Applying $x"
-		patch -p1 --forward < $x || true
-	done
-
-	# TODO: this is probably wrong
-	if [ $BASEBOARD = kukui ]; then
-		patch -p1 --forward < $CADMIUMROOT/kernel/patches/android-enable-building-ashmem-and-binder-as-modules.patch || true
-		patch -p1 --forward < $CADMIUMROOT/kernel/patches/export-symbols-needed-by-android-drivers.patch || true
-	else
-		patch -p1 --forward < $CADMIUMROOT/kernel/patches/android-enable-building-ashmem-and-binder-as-modules.patch || true
-		patch -p1 --forward < $CADMIUMROOT/kernel/patches/export-symbols-needed-by-android-drivers.patch.alt || true
-	fi
+			# TODO: this is probably wrong
+			if [ $BASEBOARD = kukui ]; then
+				patch -p1 --forward < $CADMIUMROOT/kernel/patches/android-enable-building-ashmem-and-binder-as-modules.patch || true
+				patch -p1 --forward < $CADMIUMROOT/kernel/patches/export-symbols-needed-by-android-drivers.patch || true
+			else
+				patch -p1 --forward < $CADMIUMROOT/kernel/patches/android-enable-building-ashmem-and-binder-as-modules.patch || true
+				patch -p1 --forward < $CADMIUMROOT/kernel/patches/export-symbols-needed-by-android-drivers.patch.alt || true
+			fi
+		;;
+	esac
 fi
 
 cd $CADMIUMROOT/tmp/linux-$BASEBOARD
