fs/install: refuse to install if device is not charged

diff --git a/fs/install b/fs/install
--- a/fs/install
+++ b/fs/install
@@ -44,6 +44,30 @@ fi
 . $CADMIUMROOT/baseboard/$BASEBOARD/boardinfo
 #echo "$SOC $BOARD $BASEBOARD"
 
+# don't even try installing if the device is about to die
+for x in /sys/class/power_supply/*; do
+	echo "Trying path: $x"
+	if [ "$(cat $x/device/name)" = 'sbs-battery' -o "$(cat $x/device/name)" = 'bq27500' ]; then
+		echo "Found battery at $x"
+		BAT=$x
+	fi
+done
+
+if [ "$BAT" = "NOTFOUND" ]; then
+	. /CdFiles/info
+	echo "Debug info: K: $KERNEL R: $ROOTFS B: $BASEBOARD T: $BOARD"
+	echo "Uh oh, automatic battery detection failed"
+	echo "Make a photo of this screen and include it in issue on Cadmium Github page"
+fi
+
+BATCAPACITY="$(cat $BAT/capacity)"
+
+if [ "$BATCAPACITY" -le 40 ]; then
+	echo "Looks like your device is about to discharge"
+	echo "Bailing out for safety reasons"
+	exit 1
+fi
+
 if [ "$BASEBOARD" = "trogdor" ]; then
 	make -j$(nproc) -C /CdFiles/qmic install prefix=/usr
 	echo qmic >> /CdFiles/installed_progs
